version: "3.8"

networks:
  scoretracking-net:
    driver: bridge

services:
  api:
    container_name: scoretracking-api
    build:
      context: ./components/api
      dockerfile: Dockerfile
      target: runtime
      args:
        BUILD_CONFIGURATION: Debug
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:80
      # Logging__LogLevel__Microsoft.AspNetCore: Debug
    ports:
      - 5000:80
    depends_on:
      database:
        condition: service_healthy
    networks:
      - scoretracking-net
    healthcheck:
      test: wget -nv -t1 --spider http://localhost:80/swagger/index.html || exit 1
      interval: 10s
      timeout: 20s
      retries: 3

  database:
    image: postgres:latest
    container_name: scoretracking-database
    restart: on-failure
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - 5432:5432
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - scoretracking-net
    logging:
      driver: "json-file"
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 20s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: scoretracking-pgadmin
    restart: on-failure
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@scoretracking.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050
    networks:
      - scoretracking-net
    volumes:
      - pgadmin_volume:/var/lib/pgadmin
    logging:
      driver: "none"

  redis_image:
    image: redis
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - scoretracking-net
    volumes:
      - redis_volume:/var/lib/redis/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq_queue
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASSWORD
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - scoretracking-net

volumes:
  database_volume:
  pgadmin_volume:
  redis_volume:
  rabbitmq_data:
